name: Build and push docker image

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_ACCOUNT_ID }}
          password: ${{ secrets.DOCKER_ACCOUNT_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_ACCOUNT_ID }}/healthcheck-base:${{ github.sha }}, ${{ secrets.DOCKER_ACCOUNT_ID }}/healthcheck-base:latest
